import AppKit
import Combine

struct ClipboardItem: Identifiable {
    let id = UUID()
    let content: Content
    let date: Date

    enum Content {
        case text(String)
        /// Miniatura per la UI + dati compressi originali per il re-copy:
        /// tenere NSImage a piena risoluzione costava decine di MB a screenshot.
        case image(thumbnail: NSImage, data: Data, type: NSPasteboard.PasteboardType)

        var previewText: String {
            switch self {
            case .text(let s):  return s
            case .image:        return "Immagine"
            }
        }
    }
}

final class ClipboardMonitor: ObservableObject {
    @Published var items: [ClipboardItem] = []

    private var lastChangeCount: Int = -1
    private var timer: Timer?
    private let maxItems = 10

    /// Convenzione standard (nspasteboard.org): i password manager marcano
    /// così i contenuti sensibili o transitori — non vanno mai in cronologia.
    private static let excludedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    init() { start() }
    deinit { timer?.invalidate() }

    func start() {
        guard timer == nil else { return }

        let t = Timer.scheduledTimer(withTimeInterval: 1.6, repeats: true) { [weak self] _ in
            self?.poll()
        }
        t.tolerance = 0.4
        timer = t
    }

    func clear() { items = [] }

    func copy(_ item: ClipboardItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.content {
        case .text(let s):
            pb.setString(s, forType: .string)
        case .image(_, let data, let type):
            pb.setData(data, forType: type)
        }
        // Non ri-catturare quello che abbiamo appena rimesso noi nel pasteboard.
        lastChangeCount = pb.changeCount
    }

    // MARK: - Poll

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let types = pb.types ?? []
        guard !Self.excludedTypes.contains(where: types.contains) else { return }

        if let str = pb.string(forType: .string), !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            // Evita duplicati consecutivi
            if case .text(let last) = items.first?.content, last == str { return }
            prepend(ClipboardItem(content: .text(str), date: Date()))
            return
        }

        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            guard let data = pb.data(forType: type), let image = NSImage(data: data) else { continue }
            // Evita duplicati consecutivi
            if case .image(_, let lastData, _) = items.first?.content, lastData == data { return }
            let thumb = image.resizedBitmap(maxSide: 160)
            prepend(ClipboardItem(content: .image(thumbnail: thumb, data: data, type: type), date: Date()))
            return
        }
    }

    private func prepend(_ item: ClipboardItem) {
        items.insert(item, at: 0)
        if items.count > maxItems { items = Array(items.prefix(maxItems)) }
    }
}
