import AppKit
import Combine

struct ClipboardItem: Identifiable {
    var id = UUID()
    var isFavorite = false
    let content: Content
    var date: Date

    enum Content {
        case text(String)
        /// Miniatura per la UI + dati compressi originali per il re-copy:
        /// tenere NSImage a piena risoluzione costava decine di MB a screenshot.
        case image(thumbnail: NSImage, data: Data, type: NSPasteboard.PasteboardType)

        var previewText: String {
            switch self {
            case .text(let s):  return s
            case .image:        return "Immagine"
            }
        }
    }
}

final class ClipboardMonitor: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []
    @Published var message: String?

    private var lastChangeCount: Int = -1
    private var timer: Timer?
    private let maxItems = 30
    private let maxRecentBytes: Int
    private let maxItemBytes = 16 * 1024 * 1024
    private let defaults: UserDefaults
    private let favoritesKey = "clipboard.favorites.v1"
    private struct SavedFavorite: Codable {
        var id: UUID
        var date: Date
        var text: String?
        var data: Data?
        var type: String?
    }

    /// Convenzione standard (nspasteboard.org): i password manager marcano
    /// così i contenuti sensibili o transitori — non vanno mai in cronologia.
    private static let excludedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    init(defaults: UserDefaults = .standard, startMonitoring: Bool = true, memoryBudget: Int = 64 * 1024 * 1024) {
        self.defaults = defaults
        self.maxRecentBytes = max(0, memoryBudget)
        if let data = defaults.data(forKey: favoritesKey),
           let saved = try? JSONDecoder().decode([SavedFavorite].self, from: data) {
            items = saved.compactMap { entry in
                let content: ClipboardItem.Content
                if let text = entry.text { content = .text(text) }
                else if let data = entry.data, let type = entry.type, let image = NSImage.clipboardThumbnail(data: data) {
                    content = .image(thumbnail: image, data: data, type: .init(type))
                } else { return nil }
                return ClipboardItem(id: entry.id, isFavorite: true, content: content, date: entry.date)
            }
        }
        if startMonitoring { start() }
    }
    deinit { timer?.invalidate() }

    func start() {
        guard timer == nil else { return }

        let t = Timer.scheduledTimer(withTimeInterval: 1.6, repeats: true) { [weak self] _ in
            self?.poll()
        }
        t.tolerance = 0.4
        timer = t
    }

    func clear() { items.removeAll { !$0.isFavorite } }

    /// I recenti scadono a mezzanotte nel fuso orario locale; i preferiti restano.
    func clearExpiredItems(now: Date = Date(), calendar: Calendar = .current) {
        let startOfToday = calendar.startOfDay(for: now)
        if items.contains(where: { !$0.isFavorite && $0.date < startOfToday }) {
            items.removeAll { !$0.isFavorite && $0.date < startOfToday }
        }
    }

    func filtered(query: String, favoritesOnly: Bool) -> [ClipboardItem] {
        let term = query.trimmingCharacters(in: .whitespacesAndNewlines)
        return items.filter { (!favoritesOnly || $0.isFavorite) &&
            (term.isEmpty || $0.content.previewText.localizedStandardContains(term)) }
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        saveFavorites()
    }

    func toggleFavorite(_ item: ClipboardItem) {
        guard let i = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[i].isFavorite.toggle()
        if !saveFavorites() {
            items[i].isFavorite.toggle()
            message = "Preferiti pieni: rimuovi qualche elemento (massimo 30 elementi / 16 MB)."
        }
        trimHistory()
    }

    @discardableResult
    private func saveFavorites() -> Bool {
        let favorites = items.filter(\.isFavorite)
        guard favorites.count <= 30 else { return false }
        let saved = favorites.map { item -> SavedFavorite in
            switch item.content {
            case .text(let text): return SavedFavorite(id: item.id, date: item.date, text: text)
            case .image(_, let data, let type): return SavedFavorite(id: item.id, date: item.date, data: data, type: type.rawValue)
            }
        }
        guard let data = try? JSONEncoder().encode(saved), data.count <= 16 * 1024 * 1024 else { return false }
        defaults.set(data, forKey: favoritesKey)
        return true
    }

    func copy(_ item: ClipboardItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.content {
        case .text(let s):
            pb.setString(s, forType: .string)
        case .image(_, let data, let type):
            pb.setData(data, forType: type)
        }
        // Non ri-catturare quello che abbiamo appena rimesso noi nel pasteboard.
        lastChangeCount = pb.changeCount
    }

    // MARK: - Poll

    private func poll() {
        // Controllare anche se il pasteboard non cambia, incluso dopo lo standby.
        clearExpiredItems()
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let types = pb.types ?? []
        guard !Self.excludedTypes.contains(where: types.contains) else { return }

        if let str = pb.string(forType: .string), !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            // Evita duplicati consecutivi
            if case .text(let last) = items.first?.content, last == str { return }
            prepend(ClipboardItem(content: .text(str), date: Date()))
            return
        }

        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            guard let data = pb.data(forType: type), data.count <= maxItemBytes, let image = NSImage.clipboardThumbnail(data: data) else { continue }
            // Evita duplicati consecutivi
            if case .image(_, let lastData, _) = items.first?.content, lastData == data { return }
            let thumb = image
            prepend(ClipboardItem(content: .image(thumbnail: thumb, data: data, type: type), date: Date()))
            return
        }
    }

    private func byteCount(_ item: ClipboardItem) -> Int {
        switch item.content {
        case .text(let text): return text.utf8.count
        case .image(_, let data, _): return data.count
        }
    }

    func prepend(_ item: ClipboardItem) {
        guard byteCount(item) <= maxItemBytes else {
            message = "Elemento troppo grande per la cronologia (massimo 16 MB). Rimane disponibile negli appunti di sistema."
            return
        }
        // Un contenuto ricopiato conserva il suo preferito e non crea doppioni.
        if let index = items.firstIndex(where: { existing in
            switch (existing.content, item.content) {
            case (.text(let a), .text(let b)): return a == b
            case (.image(_, let a, _), .image(_, let b, _)): return a == b
            default: return false
            }
        }) {
            var existing = items.remove(at: index)
            existing.date = item.date
            items.insert(existing, at: 0)
        } else { items.insert(item, at: 0) }
        trimHistory()
    }

    private func trimHistory() {
        var recent = 0
        var bytes = 0
        items = items.filter { item in
            if item.isFavorite { return true }
            recent += 1
            bytes += byteCount(item)
            return recent <= maxItems && bytes <= maxRecentBytes
        }
    }
}
